name: tf
channels:
  - intel
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _py-xgboost-mutex
  - abseil-cpp
  - absl-py
  - aiohttp
  - aiohttp-cors
  - aioredis
  - alembic
  - alsa-lib
  - altair
  - ansi2html
  - anyio
  - argcomplete
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow-cpp
  - astor
  - asttokens
  - astunparse
  - async-timeout
  - atk
  - atk-1.0
  - attrs
  - autopage
  - autopep8
  - aws-c-cal
  - aws-c-common
  - aws-c-event-stream
  - aws-c-io
  - aws-checksums
  - aws-sdk-cpp
  - babel
  - backcall
  - beautifulsoup4
  - bidict
  - black
  - blackd
  - blas
  - bleach
  - blinker
  - bokeh
  - boost-cpp
  - bottleneck
  - brotli
  - brotli-python
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cachetools
  - cairo
  - catboost
  - category_encoders
  - certifi
  - cffi
  - chardet
  - chart-studio
  - click
  - cliff
  - cloudpickle
  - cmaes
  - cmd2
  - colorama
  - colorlog
  - colour
  - composeml
  - contextlib2
  - convertdate
  - coverage
  - cryptography
  - cycler
  - cython
  - cytoolz
  - daal4py
  - dal
  - dash
  - dash-auth
  - dash-bootstrap-components
  - dash-core-components
  - dash-daq
  - dash-html-components
  - dash-renderer
  - dash-table
  - dash_colorscales
  - dask
  - dask-core
  - dataclasses
  - dbus
  - debugpy
  - decorator
  - defusedxml
  - distributed
  - dnspython
  - dpcpp-cpp-rt
  - dpcpp_cpp_rt
  - dpctl
  - dpnp
  - dtale
  - dtreeviz
  - email-validator
  - entrypoints
  - et_xmlfile
  - executing
  - expat
  - explainerdashboard
  - featuretools
  - ffmpeg
  - filelock
  - flask
  - flask-compress
  - flask-cors
  - flask-seasurf
  - flask-socketio
  - flask-wtf
  - flask_cors
  - flask_simplelogin
  - flatbuffers
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-anaconda
  - fonts-conda-ecosystem
  - fonttools
  - fortran_rt
  - freeglut
  - freetype
  - fribidi
  - fsspec
  - future
  - g-ir-build-tools
  - g-ir-host-tools
  - gast
  - gdk-pixbuf
  - gettext
  - gevent
  - gevent-websocket
  - gflags
  - giflib
  - glib
  - glib-tools
  - glog
  - gmp
  - gnutls
  - gobject-introspection
  - google-auth
  - google-auth-oauthlib
  - google-pasta
  - graphite2
  - graphviz
  - greenlet
  - grpc-cpp
  - grpcio
  - gst-plugins-base
  - gstreamer
  - gtk2
  - gts
  - h5py
  - harfbuzz
  - hdf5
  - heapdict
  - hijri-converter
  - hiredis
  - holidays
  - htmlmin
  - hyperopt
  - icc_rt
  - icu
  - idna
  - imagehash
  - impi-devel
  - impi_rt
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - iniconfig
  - intel-aikit-tensorflow
  - intel-cmplr-lib-rt
  - intel-cmplr-lic-rt
  - intel-fortran-rt
  - intel-opencl-rt
  - intel-openmp
  - intelpython
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - iso3166
  - isort
  - itsdangerous
  - jasper
  - jbig
  - jedi
  - jinja2
  - joblib
  - jpeg
  - json5
  - jsonpath-ng
  - jsonschema
  - jupyter
  - jupyter-dash
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kaggle
  - keras
  - keras-preprocessing
  - kiwisolver
  - korean_lunar_calendar
  - krb5
  - lame
  - lcms2
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libevent
  - libffi
  - libgcc-ng
  - libgd
  - libgfortran-ng
  - libgfortran5
  - libgirepository
  - libglib
  - libglu
  - libgomp
  - libiconv
  - libidn2
  - liblapack
  - liblapacke
  - libllvm10
  - libllvm11
  - libnghttp2
  - libopenblas
  - libopencv
  - libpng
  - libpq
  - libprotobuf
  - librsvg
  - libsodium
  - libssh2
  - libstdcxx-ng
  - libtasn1
  - libthrift
  - libtiff
  - libtool
  - libunistring
  - libutf8proc
  - libuuid
  - libuv
  - libwebp
  - libwebp-base
  - libxcb
  - libxgboost
  - libxkbcommon
  - libxml2
  - libzlib
  - lightgbm
  - llvm-spirv
  - llvmlite
  - locket
  - lz4
  - lz4-c
  - mako
  - markdown
  - markupsafe
  - matplotlib
  - matplotlib-base
  - matplotlib-inline
  - metaphone
  - missingno
  - mistune
  - mkl
  - mkl-devel
  - mkl-devel-dpcpp
  - mkl-dpcpp
  - mkl-include
  - mkl-service
  - mkl_fft
  - mkl_random
  - mkl_umath
  - mljar-supervised
  - modin-core
  - modin-ray
  - mpi4py
  - msgpack-python
  - multidict
  - multimethod
  - multipledispatch
  - munkres
  - mypy_extensions
  - mysql-common
  - mysql-libs
  - natsort
  - nbclassic
  - nbclient
  - nbconvert
  - nbformat
  - ncurses
  - nest-asyncio
  - nettle
  - networkx
  - neural-compressor
  - ninja
  - nltk
  - nodejs
  - notebook
  - nspr
  - nss
  - numba
  - numba-dppy
  - numexpr
  - numpy
  - numpy-base
  - oauthlib
  - olefile
  - onednn-cpu-dpcpp-gpu-dpcpp
  - onednn-devel-cpu-dpcpp-gpu-dpcpp
  - opencv
  - openh264
  - openpyxl
  - openssl
  - opt_einsum
  - optuna
  - orc
  - oyaml
  - packaging
  - pandas
  - pandas-flavor
  - pandas-profiling
  - pandas-stubs
  - pandas-summary
  - pandocfilters
  - pango
  - parso
  - partd
  - pathspec
  - patsy
  - pbr
  - pcre
  - pexpect
  - phik
  - pickleshare
  - pillow
  - pip
  - pixman
  - pkg-config
  - platformdirs
  - plotly
  - pluggy
  - ply
  - prettytable
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - protobuf
  - psutil
  - ptyprocess
  - pure_eval
  - py
  - py-cpuinfo
  - py-opencv
  - py-xgboost
  - pyarrow
  - pyasn1
  - pyasn1-modules
  - pycocotools
  - pycodestyle
  - pycparser
  - pydantic
  - pygments
  - pyjanitor
  - pyjwt
  - pymeeus
  - pymongo
  - pyopenssl
  - pyparsing
  - pyperclip
  - pyqt
  - pyqt-impl
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - pyrsistent
  - pysocks
  - pytest
  - python
  - python-crfsuite
  - python-dateutil
  - python-engineio
  - python-fastjsonschema
  - python-flatbuffers
  - python-graphviz
  - python-levenshtein
  - python-slugify
  - python-socketio
  - python-stdnum
  - python_abi
  - pytorch
  - pytorch-mutex
  - pytz
  - pywavelets
  - pyyaml
  - pyzmq
  - qt
  - qtconsole
  - qtconsole-base
  - qtpy
  - ray-core
  - re2
  - readline
  - redis-py
  - regex
  - requests
  - requests-oauthlib
  - retrying
  - rsa
  - s2n
  - schema
  - scikit-learn
  - scikit-learn-intelex
  - scikit-plot
  - scipy
  - seaborn
  - send2trash
  - setproctitle
  - setuptools
  - sh
  - shap
  - sigopt
  - six
  - slicer
  - snappy
  - sniffio
  - sortedcontainers
  - soupsieve
  - spirv-tools
  - sqlalchemy
  - sqlite
  - squarify
  - stack_data
  - statsmodels
  - stevedore
  - strsimpy
  - tabulate
  - tangled-up-in-unicode
  - tbb
  - tbb4py
  - tblib
  - tcl
  - tenacity
  - tensorboard
  - tensorboard-data-server
  - tensorboard-plugin-wit
  - tensorflow
  - tensorflow-estimator
  - termcolor
  - terminado
  - testpath
  - text-unidecode
  - threadpoolctl
  - tk
  - toml
  - tomli
  - toolz
  - tornado
  - tqdm
  - traitlets
  - typed-ast
  - typing-extensions
  - typing_extensions
  - ua-parser
  - unidecode
  - urllib3
  - varname
  - visions
  - waitress
  - wcwidth
  - webencodings
  - websocket-client
  - werkzeug
  - wheel
  - widgetsnbextension
  - woodwork
  - wordcloud
  - wrapt
  - wtforms
  - x264
  - xarray
  - xgboost
  - xlrd
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxpm
  - xorg-libxrender
  - xorg-libxt
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - yaml
  - yarl
  - zeromq
  - zict
  - zipp
  - zlib
  - zope.event
  - zope.interface
  - zstd
